# Generated by Django 4.2.7 on 2023-11-07 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytopicpreferences',
            name='study_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studytopic'),
        ),
    ]
